config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :kanjis

  resources :words
  
  patch '/kanjis/:id(.:format)', to: 'kanjis#learned' 
  post 'tmpincr', to: 'words#tmpincr'
  post 'stream', to: 'words#stream'
  get 'stream', to: 'words#stream'
  get '/kanjis/:id(.:format)/getWords', to: 'words#indexSome' 
  get '/words/:id(.:format)/incrementdue', to: 'words#incrementdue', as: :incrementDue_word 
  get '/ang', to: 'words#index1' 
  get '/tmp', to: 'words#tmp' 
  get '/react', to: 'words#react' 
  get '/study', to: 'words#study' 
  get '/play', to: 'words#play' 
  root to: 'words#study'

end

app/models/kanji.rb
class Kanji < ActiveRecord::Base
#belongs_to :word
  has_and_belongs_to_many :words

def getWords
  #Word.joins(:kanjis).where(kanjis: {kanji: self.kanji});
  self.words
end

end

app/controllers/kanjis_controller.rb
class KanjisController < ApplicationController
  before_action :set_kanji, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /kanjis
  # GET /kanjis.json
  def index
    if params[:word_id]
      @kanjis = Word.find(params[:word_id]).kanjis;
    else
      #@kanjis = Kanji.where("learned =  'false'").group(:kanji).order(:id).reverse_order()
     ## @kanjis = Kanji.where("learned =  'false'").order(:id).reverse_order()
      @kanjis = Kanji.joins(:words).group("kanji_id") .order("COUNT(*) DESC")
      
    end
  end

  # GET /kanjis/1
  # GET /kanjis/1.json
  def show
  end

  # GET /kanjis/new
  def new
    @kanji = Kanji.new
  end

  # GET /kanjis/1/edit
  def edit
  end

  # POST /kanjis
  # POST /kanjis.json
  def create
    @kanji = Kanji.new(kanji_params)

    respond_to do |format|
      if @kanji.save
        format.html { redirect_to @kanji, notice: 'Kanji was successfully created.' }
        format.json { render :show, status: :created, location: @kanji }
      else
        format.html { render :new }
        format.json { render json: @kanji.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kanjis/1
  # PATCH/PUT /kanjis/1.json
  def update
    respond_to do |format|
      if @kanji.update(kanji_params)
        format.html { redirect_to action: "index" }
        format.json { render :show, status: :ok, location: @kanjis }
      else
        format.html { render :edit }
        format.json { render json: @kanji.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kanjis/1
  # DELETE /kanjis/1.json
  def destroy
    @kanji.destroy
    respond_to do |format|
      format.html { redirect_to kanjis_url, notice: 'Kanji was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def learned
    @kanji.learned = true
    @kanji.save
    respond_to do |format|
      format.html { redirect_to kanjis_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kanji
      @kanji = Kanji.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kanji_params
      params.require(:kanji).permit(:kanji, :due, :learned)
    end
end

app/helpers/kanjis_helper.rb
module KanjisHelper
end

app/views/kanjis/.#show.html.erb
benyx@benyx-UX31A.5531:1433026313

app/views/kanjis/_form.html.erb
<%= form_for(@kanji) do |f| %>
  <% if @kanji.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kanji.errors.count, "error") %> prohibited this kanji from being saved:</h2>

      <ul>
      <% @kanji.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kanji %><br>
    <%= f.text_field :kanji %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kanjis/edit.html.erb
<h1>Editing Kanji</h1>

<%= render 'form' %>

<%= link_to 'Show', @kanji %> |
<%= link_to 'Back', kanjis_path %>

app/views/kanjis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kanjis</h1>

<table style="margin-left: 200px;width: 1000px;     text-decoration: none;">
  <thead>
    <tr>
      <th>Kanji</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kanjis.each_with_index do |kanji, index| %>
    <% next if kanji.learned %>
    <%= if index%10 == 0 then raw('<tr>') end %>
    <td style="text-decoration: none;">
      <%= link_to ("http://jisho.org/search/%23kanji%20#{kanji.kanji}") do %>
      <font color="red" size="20px"><%= kanji.kanji %></font> 
      <% end %>
      </td> 
    <td><%= link_to "Words(#{kanji.getWords().count})", :controller => "words", :action => "indexSome", :id => kanji.id %>
      <%= link_to  "Learned", kanji_path(kanji, :kanji => {:learned => true} ),  :method => "patch"   %></td>
      <%= if index%10 == 9 then raw('</tr>') end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kanji', new_kanji_path %>

app/views/kanjis/new.html.erb
<h1>New Kanji</h1>

<%= render 'form' %>

<%= link_to 'Back', kanjis_path %>

app/views/kanjis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kanji:</strong>
  <%= @kanji.kanji %>
</p>

<p>
  <strong>Due:</strong>
  <%= @kanji.due %>
</p>

<%= link_to 'Edit', edit_kanji_path(@kanji) %> |
<%= link_to 'Back', kanjis_path %>