config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :kanjis

  resources :words
  
  patch '/kanjis/:id(.:format)', to: 'kanjis#learned' 
  post 'tmpincr', to: 'words#tmpincr'
  post 'stream', to: 'words#stream'
  get 'stream', to: 'words#stream'
  get '/kanjis/:id(.:format)/getWords', to: 'words#indexSome' 
  get '/words/:id(.:format)/incrementdue', to: 'words#incrementdue', as: :incrementDue_word 
  get '/ang', to: 'words#index1' 
  get '/tmp', to: 'words#tmp' 
  get '/react', to: 'words#react' 
  get '/study', to: 'words#study' 
  get '/play', to: 'words#play' 
  root to: 'words#study'

end

app/models/word.rb
class Word < ActiveRecord::Base

  has_and_belongs_to_many :kanjis
#  validates_uniqueness_of :word
  
  def after_initialize
    self.gross =     getTranslation()[1]
  end

  def getKanjis
    #Kanji.find_by(word_id: self.word_id);
    self.kanjis
  end

  def createLinks
    self.word.each_char do |i|
      if ""+i =~ /\p{Han}/
        #unless Kanji.find_by_kanji
        kanji = Kanji.find_by_kanji(""+i)
        unless kanji != nil
          kanji = Kanji.new 
          kanji.kanji = ""+i
          kanji.save
        end
        self.kanjis << kanji;
      end
    end
  end

  def self.getAdded 
    Word.where("due = '1972-06-23'")
  end
  
  def self.setAdded
    Word.all.each() do |word|
      word.due =  '1972-06-23'
      word.save
    end
  end
  
  def self.allocateNew
    currentNewCount = Word.getNew().count;
    Word.getAdded().limit(20 - currentNewCount).each() do |word|
      word.due =  '2012-06-23'
      word.save
    end
  end


    
  def self.getNew 
    Word.where("due =  '2012-06-23'")
  end
  
  def isNew? 
    self.due == DateTime.parse('2012-06-23')
  end
  

  def isInLearn? 
    self.due == DateTime.parse('2013-06-23')
  end
  

  def self.getInLearn 
      Word.where("due = '2013-06-23'").order(:duetime);
  end

  def setInLearn(inMinutes)
    self.duetime = Time.current() + inMinutes.minutes    
    self.due = '2013-06-23'
    self.lastdelay = inMinutes
  end
  
  ## 10m -> 
  def getOptions()
    ret = Hash.new(0)
    if isNew? 
      ret = {"again" => 1, "good" => 10, "easy" => 24 * 60} 
    elsif isInLearn?  
      ret = {"again" => self.lastdelay, "good" => 24 * 60} 
    else 
      ret = {"again" => 10, "hard" => self.lastdelay, 
          "good" => self.lastdelay*2, "easy" => self.lastdelay * 3} 
    end
    
    return ret
  end

  ##@@dues
  def self.getDue 
    ##@@dues ||= 
    Word.where("due >  '2013-06-23' AND due <= ? ", Date.today)
  end

  def isDue? 
    (self.due > Date.parse('2013-06-23')) && (self.due <= Date.today)
  end

  def self.getNewerThan(atime) 
    Word.where("created_at > ?", atime)
  end
  
  def getTranslation
    mean = Edict.meaning(word) 
    if ( mean.count == 0)
      mean = Edict.meaning_by_hiragana(word) 
    end

    if mean != nil && mean.count && mean[0] != nil
      return mean[0]
    end
    return ["", ""];
  end
  
  def getMeaning
    self.gross
  end

  def getFurigana
    #getTranslation()[0]
  end
  
  
  def incrementDue(plusDue)
    puts self.due
    if plusDue.to_i <= 10
      self.setInLearn(plusDue.to_i)
    else
      
      self.due = Date.today() + plusDue.to_i.minutes
      
      self.lastdelay = plusDue
      puts self.due
    end
  end

  
  def self.getCurrentWord
    
    word = nil

    if (Word.getInLearn.count > 0 && Word.getInLearn[0].duetime <= DateTime.now) then
      word = Word.getInLearn[0];
    elsif  (Word.getDue.count > 0) then
      word = Word.getDue[0];
    elsif (Word.getNew.count > 0) then
      word = Word.getNew[0];
    end
    if word == nil && Word.getInLearn.count > 0
      word = Word.getInLearn[0];
    end

    #p "After #{word.due}"
    
    return word
  end
  
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  ##after_action :u, only: [:edit, :update, :stream, :new, :create]

  protect_from_forgery except: :stream

  skip_before_filter :verify_authenticity_token
  
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers
 
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
    headers['Access-Control-Max-Age'] = "1728000"
  end
 
  def cors_preflight_check
    if request.method == 'OPTIONS'
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Token'
      headers['Access-Control-Max-Age'] = '1728000'
 
      render :text => '', :content_type => 'text/plain'
    end
  end


  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  ##test
  def react
  end

  ##test
  def tmp
#    @words = Word.find(params[:id]);
  end
  
  ##test
  def tmpincr
    @word = Word.find_by_word(params[:name])
    @word.incrementDue(rand(10)*60*24);
    @word.save
  end
  
  # GET /words/play

  def play  
    @words = Word.all;
  end
  
  
  def incrementdue 
    @word = Word.find(params[:id]);
    @word.incrementDue(params[:level]);
    @word.save
    redirect_to action: params[:task], continue: '1'  
  end

  
  def indexSome
    @kanji = Kanji.find(params[:id]);
    @words = @kanji.getWords
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @task = "show"
  end

  # GET /words/new
  def new
    @word = Word.new
    @words = Word.all
  end

  # GET /words/1/edit
  def edit
    
  end

  def study
    if params[:currentIdx] 
      Word.allocateNew
    end
    @news = Word.getNew
    @inLearn = Word.getInLearn
    @dues = Word.getDue
    @word = Word.getCurrentWord
    @task = "study"
  end 

  ## API method 
  def stream
    response.headers['Content-Type'] = 'text/plain'    
    unless Word.find_by_word(params[:word]) 
      @word = Word.new()
      @word.word = params[:word];
      @word.createLinks
      @word.save
      
      response.stream.write "You added----->"+ params[:word] + ". Thank you!!"
    else
      response.stream.write "Word exists. Thank you!!"
      
    end
    
  ensure
    response.stream.close
  end
  

  def update_kanji()
    Word.find_each() do |word|
      word.createLinks
    end
  end

  
  # POST /words
  # POST /words.json
  def create
    
    @word = Word.new(word_params)
    @words = Word.all
    @word.createLinks
      
    begin
      @word.save
      puts @word.errors.full_messages
      redirect_to action: "new", notice: 'Pedido enviado com sucesso.'  
      #  format.json { render :show, status: :created, location: @word }
    rescue ActiveRecord::RecordNotUnique => e
      @word.errors.add(@word.word, "Exists already") 
      #@word.errors = 'Exist.' 
      render :edit 
      #redirect_to action: "new", @word, notice: 'Exist.' 
    end
  end
  

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    @word.kanjis.clear
    respond_to do |format|
      if @word.update(word_params) && @word.createLinks
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word, :due)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<div style="font-size: 30px; margin-left: 200px">
<h1>New Word</h1>
<%= render 'form' %>

<%= link_to 'Back', words_path %>

</div>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>



<table style="font-size: 20px; margin-left: 200px">
  <thead>
    <tr>
      <th>Word</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody style="font-family: TakaoExGothic">
    <% @words.reverse_order.each do |word| %>
      <tr>
	<td>
	  <font color="red" size="20px">
	    <%= word.word %>
	  </font> 
	</td>
        
	<% if word != nil %>
	<td><%= link_to 'Show', word_path(word) %></td>
	<% end %>
        <td><%= link_to 'Kill', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/words/indexSome.html.erb
index.html.erb

app/views/words/index_some.html.erb
<p id="notice"><%= notice %></p>

<h1>@kanji.kanji</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= word.due %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<%= javascript_tag do %>

window.onload = function() {


document.getElementById("word_word").focus();
}


<% end %>
<div style="font-size: 30px; margin-left: 200px">
<h1>New Word</h1>
<%= render 'form' %>
<%= @words.count %>
<%= link_to 'Back', words_path %>

<%= render :template => 'words/index' -%>

</div>

app/views/words/play.html.erb
<p id="notice"><%= notice %></p>



<script src="http://code.responsivevoice.org/responsivevoice.js"></script>

<%= javascript_tag do %>


function player() { 

var i = 0;
var on = false;
var pp = null;
var timer;

var array = [];
<% @words.shuffle.each do |word| %>
array.push('<%=word.word%>');
<% end %>


var tt = {

stopPlay: function () { 
pp = pp ||  document.getElementById("Played");
  console.log("STOP");
  on = ! on; 
  

  if (on) {

    timer = setInterval( function() {
      i = i % array.length;
      pp.innerHTML = array[i]; 
      responsiveVoice.speak(array[i++], 'Japanese Female');
    } , 3000);
 
  } else {
    clearTimeout(timer);  
  } 
}, 

move: function(inc) {
  pp = pp ||  document.getElementById("Played");
  i += inc;
  i = i % array.length;
  pp.innerHTML = array[i]; 
}

}; 

return tt; }

var p = new player();




document.onkeydown = function(e) {
e = e || event; // "real browsers" || IE6/7.


if (e.keyCode == 32) { 
 p.stopPlay();

}
}

function OnPlay() {
p.stopPlay();
}

function OnForw() {
p.move(1);
}

<% end %>



<div style="margin-left: 500px;margin-top: 100px;width: 800px;     text-decoration: none; border:1px solid black;">
  <div id="header" style="text-align:center;">
    
    <font color="red" size="7">  
      <p id="Played" style="font-size:100px;font-family: TakaoExGothic;">
      </p>
    </font>
    
  </div>

  <button onclick="p.move(-1)"><<<<<</button>
  <button onclick="OnForw()">>>>></button>
  <button onclick="OnPlay()">Play-Stop</button>
  
</div>

app/views/words/react.html.erb
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>Hello React</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/JSXTransformer.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  </head>
  <body>
    <div id="content"></div>
    <script type="text/jsx">
      
      var Comment = React.createClass({
      render: function() {
      return (
      <div className="comment">
        <h2 className="commentAuthor">
          {this.props.author}
        </h2>
        {this.props.children}
      </div>
      );
      }
      });
      
      var CommentList = React.createClass({
      render: function() {
      return (
      <div className="commentList">
	<Comment author="Pete Hunt">This is one comment</Comment>
        <Comment author="Jordan Walke">This is *another* comment</Comment>
      </div>
      );
      }
      });
      
      var CommentForm = React.createClass({
      render: function() {
      return (
      <div className="commentForm">
        Hello, world! I am a CommentForm.
      </div>
      );
      }
      });
      // Your code here
      var CommentBox = React.createClass({
      render: function() {
      return (
      <div className="commentBox">
        <h1>Comments</h1>
        <CommentList />
        <CommentForm />
      </div>
      );
      }
      });
      React.render(
      
      <CommentBox />,
      document.getElementById('content')
      );
    </script>
  </body>
</html>

app/views/words/show.html.erb
<script src="http://code.responsivevoice.org/responsivevoice.js"></script>

<%= javascript_tag do %>

document.onkeydown = function(e) {
e = e || event; // "real browsers" || IE6/7
if (e.keyCode == 32 || 
e.keyCode == 13) { 
var x=document.getElementById("back_card");
x.style.visibility = "visible";
} else if (e.keyCode == 83) { 
<% if @word != nil %>
responsiveVoice.speak('<%= @word.word %>', 'Japanese Female');
//var	audio =		new Audio();
//audio.src = 
//'http://translate.google.com/translate_tts?ie=utf-8&tl=ja&q=<%= @word.word %>'
//'https://translate.google.com/translate_tts?ie=UTF-8&q=<%= @word.word %>&tl=ja&<%= @word.id %>=<%= @word.id %>'
//audio.play();
<% end %>
}
}


<% end %>


<div style="margin-left: 500px;margin-top: 100px;width: 800px;     text-decoration: none; border:1px solid black;">
  <div id="header" style="text-align:center;">
    
    <font color="red" size="7">  
      <p style="font-size:100px;font-family: TakaoExGothic;">
	<%= @word.word  %>
      </p>
    </font>
    
  </div>
  
  
  <div id="section"  style="text-align:center;align:center;align:center;" >
    <div id="back_card" style="visibility: hidden;align:center;">
      <p>
	<strong>Meaning</strong>
	<%= if @word != nil then @word.getMeaning() else "Finished" end %>
      </p>
      <p>
	<strong>Furigana</strong>
	<%= @word.getFurigana %>
      </p>
      
    </div>
    <table id="section" align="center">
      <tbody>
	<tr>
	  <td bgcolor=\"blue width=566\" style=\"width:33%;padding:5px 8px;\" align=\"center\"><form> 
	      <% @word.getOptions().each do |key, array| %>
	      <%= raw("<a href=" + incrementDue_word_path(@word)+"?level="+array.to_s+"&task="+@task+
		  " style=\"width:100%;color:white;line-height:24px;\">" +
		  "<span style=\"min-width:50px;font-size:14px;font-weight:40;color:white;display:inline-block;\">" + key.to_s + "(" +array.to_s+")</span>" +
		  "</a>");
		  %>
	      <% end %>
	</tr>
      </tbody>
    </table>
  </div>
  
  <div id="footer"  style="text-align:center;">
    <%= link_to 'Edit', edit_word_path(@word) %> 
    
    <%= link_to 'Kanjis', {:controller => :kanjis, :action => :index,  :word_id => @word.id} %>
    <%= link_to 'Sentences', "http://jisho.org/search/#{@word.word}%20%23sentences"   %>
    
  </div>
</div>

app/views/words/study.html.erb
<p id="notice"><%= notice %></p>

<% if @word != nil %>
<div id="section" style="text-align:center;">
  <%= render :template => 'words/show' -%>
</div>
<% else %>
<div id="section" style="text-align:center;">
  <p> <h1>Finished</h1> </p>
</div>
<% end %>


<div id ="footer"  style="text-align:center;">
  <table align="center">
    <tbody>
      <tr>
	<td>
	  <p>
	    <%= "News("+@news.count.to_s+")" %>
	  </p>
	</td>
      <td>
	<p>
	  <%= "Learning("+@inLearn.count.to_s+")" %>
	</p>
      </td>
	<td>
	  <p>
	    <%= "Dues("+@dues.count.to_s+")" %>
	  </p>
	</td>
	<td>
	  <p>
	  </p>
	</td>
      </tr>
    </tbody>
    
  </table>  
</dev>


</dev>

app/views/words/tmp.html.erb
<p id="notice"><%= notice %></p>


<script src="http://code.responsivevoice.org/responsivevoice.js"></script>

<%= javascript_tag do %>


var ix = 0;
var pp;
var array = [];
<% Word.getAdded().each do |word| %>
array.push('<%=word.word%>');
<% end %>

window.onload = function() {
showWord();
};



function showWord() {
pp = document.getElementById("Played");
pp.innerHTML = array[ix]; 
responsiveVoice.speak(array[ix], 'Japanese Female');
}

function dontknow () {
ix++;
showWord();
}

function know () {

$.ajax({
type:'POST', 
url: '/tmpincr', 
data: $.param({ name: array[ix] })
});

ix++;
showWord();
}


<% end %>



<div style="margin-left: 500px;margin-top: 100px;width: 800px;     text-decoration: none; border:1px solid black;">
  <div id="header" style="text-align:center;">
    
    <font color="red" size="7">  
      <p id="Played" style="font-size:100px;font-family: TakaoExGothic;">
      </p>
    </font>
    
  </div>

  <button onclick="know()">Know</button>
  <button onclick="dontknow()">Dontknow</button>

  
</div>