config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :kanjis

  resources :words
  
  patch '/kanjis/:id(.:format)', to: 'kanjis#learned' 
  post 'tmpincr', to: 'words#tmpincr'
  post 'stream', to: 'words#stream'
  get 'stream', to: 'words#stream'
  get '/kanjis/:id(.:format)/getWords', to: 'words#indexSome' 
  get '/words/:id(.:format)/incrementdue', to: 'words#incrementdue', as: :incrementDue_word 
  get '/ang', to: 'words#index1' 
  get '/tmp', to: 'words#tmp' 
  get '/react', to: 'words#react' 
  get '/study', to: 'words#study' 
  get '/play', to: 'words#play' 
  root to: 'words#study'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dictionary</title>
  <%= stylesheet_link_tag    'main', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <table id="section" align="center">
    <tbody>
      <tr>
	

	<td bgcolor="blue" style="width:60%;padding:5px" align="center;">
	  <form>
	    <%= raw("<a href=" + words_path +
		" style=\"width:100%;color:white;line-height:24px;margin-left:20px;\">" +
		"<span style=\"min-width:50px;font-size:14px;font-weight:40;color:white;display:inline-block;\">Words</span>" +
		"</a>"); %>
	    <%= raw("<a href=" + kanjis_path +
		" style=\"width:100%;color:white;line-height:24px;margin-left:20px;\">" +
		"<span style=\"min-width:50px;font-size:14px;font-weight:40;color:white;display:inline-block;\">Kanjis</span>" +
		"</a>"); %>
	    <%= raw("<a href=" + new_word_path +
		" style=\"width:100%;color:white;line-height:24px;margin-left:20px;\">" +
		"<span style=\"min-width:50px;font-size:14px;font-weight:40;color:white;display:inline-block;\">Add Word</span>" +
		"</a>"); %>	    
	    <%= raw("<a href=" + study_path +
		"?currentIdx=0" +
		" style=\"width:100%;color:white;line-height:24px;margin-left:20px;\">" +
		"<span style=\"min-width:50px;font-size:14px;font-weight:40;color:white;display:inline-block;\">Study</span>" +
		"</a>"); %>
	    <%= raw("<a href=" + play_path +
		" style=\"width:100%;color:white;line-height:24px;margin-left:20px;\">" +
		"<span style=\"min-width:50px;font-size:14px;font-weight:40;color:white;display:inline-block;\">Play</span>" +
		"</a>"); %>
	  </form>
	</td>
      </tr>
    </tbody>
  </table>
  



<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div id="user_nav">
  <% if user_signed_in? %>
  Signed in as <%= current_user.email %>. This cannot be cheese?
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
  <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
    <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
= javascript_include_tag "//ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"
= javascript_include_tag "//ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular-resource.min.js"